### ISSUE TITLE
WG Region Enter event triggers when jumping at the bottom block of the region

### ISSUE THREAD

**Issue by not-3than** [SkriptLang/skript-worldguard#10]
### Description

When jumping at the lowest block in a region and jump, the region enter event triggers. This is not intended for WorldGuard itself, since WorldGuard has a "greeting-title" flag which displays a message on screen when someone enters the region, and jumping at that location triggers the Skript event, but not the greeting title.
### Steps to Reproduce

Say you have a region going from the block at x:122, y:40, z:111 to the block at x:130, y:50, z:116. If you're standing at x:126, y:39, z:112 (your 2 block tall character is fully inside the region), and you jump, the region enter event will trigger, even though you are already in the region.
1. Make a region, recreate the behavior above with a skript that tells when you enter a region.
### Expected Behavior

The event should not trigger at all.
### Errors / Screenshots

https://youtu.be/bIjlZrB9T5I

### Server Information
* **Server version/platform:** git-Paper-771 MC 1.16.5 
* **Skript version:** 2.5.3

**Comment by APickledWalrus** [comment]
Will need to investigate this issue too to make sure it hasn't already been fixed. It likely has though since this addon hooks into WorldGuard to handle this event

**Comment by APickledWalrus** [comment]
This issue seems to be fixed with this addon. The enter/leave only triggers when the player's bottom-half enters/exists the region.
