### ISSUE TITLE
Interaction with regions

### ISSUE THREAD

**Issue by PGarn** [SkriptLang/skript-worldguard#17]
Hey i'm rly sorry to write there and i'm maybe too stupid but i can't find where i can DL this addon and it seems to be the only existing one that can interact properly with WorldGuard Region. 
Maybe you know how i can DL or you know a good alternative to this.
Thanks in advance if you take time to reply

**Comment by PGarn** [comment]
For context currently i'm trying to count every entities in a region without using loop-entities to be more efficient

**Comment by APickledWalrus** [comment]
I apologize for not getting back to you on this. This addon is currently in development, but you can join our Testing Guild on Discord where we will be sharing in-progress builds before an official release is posted.
Discord Link: https://discord.gg/ZPsZAg6ygu
