### ISSUE TITLE
Error on server load, with citizens (I think)

### ISSUE THREAD

**Issue by Drakemlumme** [SkriptLang/skript-worldguard#2]
Hi, I'm using Citizens to have npc's on my rpg server.
before installing skript-worldguard, after finishing loading the server, these messages appeared: (related to npc's)
https://i.ibb.co/n6vP8m9/unknown.png
(sorry, I don't know how to put images here)
this is the error message after installing script-worldguard:
https://i.ibb.co/3Ns5NnV/unknown2.png
Luckily it didn't affect my npc's, and it doesn't seem like there was a problem with anything, but I wanted to report it.
as far as i'm concerned it seems to be a compatibility issue with citizens or similar.
Here is the full error message:
https://pastebin.com/raw/ZPkMibjL
Thanks for your time :)

**Comment by APickledWalrus** [comment]
Thanks for the report! Seems like something we should be checking for on our end (maybe citizens are crossing region borders)? Regardless, this shouldn't be too hard to fix.

**Comment by Drakemlumme** [comment]
Hello again!
>(maybe citizens are crossing region borders)?
Currently there are no NPCs with parthfinding, they are all static (most within regions)
In case you need it, here is the file with the regions (main world):
https://pastebin.com/iNM5WQML
and here is the file that saves the npc's:
https://pastebin.com/fUW18ydj

**Comment by APickledWalrus** [comment]
Sorry for the long wait! I believe this issue is fixed now with the latest commit :)

Please let me know if you have additional issues!
