### ISSUE TITLE
3 questions

### ISSUE THREAD

**Issue by davsla12** [SkriptLang/skript-worldguard#3]
is this plugin maintained?
Where can I download this plugin?
What events are there in this plugin?

**Comment by AyhamAl-Ali** [comment]
Hello,

1. Yes it's maintained, it has been extracted from Skript plugin itself and put into its own plugin to be easily maintained -- but it's currently an ALPHA version
2. The alpha version of this plugin can be [downloaded](https://discord.com/channels/988998880794402856/989002884135940246/1057331853343867010) on [Skript Testing Community](https://discord.gg/ZPsZAg6ygu) discord server
3. Same expressions/events/effects/conditions that exists in Skript. You can find them all in the [source code](https://github.com/SkriptLang/skript-worldguard/tree/main/src/main/java/org/skriptlang/skriptworldguard/elements) for now

For more info please use the former discord server to give feedback or discuss about this addon and use this issue tracker to report bugs/suggest features.

**Comment by davsla12** [comment]
What's the discord link?
