### ISSUE TITLE
Changers on members of region

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/skript-worldguard#6]
Adding a changer to support all change modes in members of region.

**Comment by APickledWalrus** [comment]
Should actually be done at https://github.com/SkriptLang/skript-worldguard/blob/main/src/main/java/org/skriptlang/skriptworldguard/elements/expressions/ExprRegionMembersOwners.java

**Comment by TheLimeGlass** [comment]
> Should actually be done at https://github.com/SkriptLang/skript-worldguard/blob/main/src/main/java/org/skriptlang/skriptworldguard/elements/expressions/ExprRegionMembersOwners.java

Was a transferred issue.

**Comment by APickledWalrus** [comment]
I will close as completed then
