### ISSUE TITLE
Rename to skript-regions

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/skript-worldguard#8]
Support all the region plugins or some from Skript

**Comment by AyhamAl-Ali** [comment]
That's gonna be hard to maintain and problematic afair we had struggles with supporting multiple region plugins in one addon, it's probably preferred to have split addons for different region plugins, easier to maintain.

**Comment by APickledWalrus** [comment]
Looking back at this, I do not think it is in our best interests to support multiple region plugins at this time. Additionally, WorldGuard is likely the most widely used. The syntax will differ with each plugin, so I think it's best to take a unique approach for any addons.
