### ISSUE TITLE
Serializer for WorldGuard regions not found

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/skript-worldguard#9]
### Description
`WorldGuardRegion`s can't be serialized even though it should be able to (`WorldGuardHook.WorldGuardRegion` extends `Region` which extends `YggdrasilExtendedSerializable`). It looks like `Yggdrasil#getSerializer(Class)` returns `null`.

### Steps to Reproduce
Use
```
on region enter:
	set {region} to event-region
```
and enter a region.

### Expected Behavior
No error and the variable is saved normally

### Errors / Screenshots
https://pastebin.com/YRPWv6wj

### Server Information
* **Server version/platform:** 1.15.2 (paper-379)
* **Skript version:** 2.5-alpha6(rev1)

### Additional Context
https://github.com/SkriptLang/Skript/issues/3185 could be related / have the same underlying issue

**Comment by APickledWalrus** [comment]
Not sure if this issue will occur with this addon - will need to verify

**Comment by Fusezion** [comment]
I remember in the past with skript using `on region enter "blah":` after reloading editing the region it no longer was accessable unless we reloaded the skript again, unsure if this is fully related to it but sounds similar to me

**Comment by APickledWalrus** [comment]
This issue appears to be resolved. I was able to set a variable to region, restart the server, and use the variable as expected.
